steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/kelseyhightower/dns01-exec-plugins.git', 'plugins/src/github.com/kelseyhightower/dns01-exec-plugins']
    id: "git-clone-dns01-exec-plugins"

  - name: "gcr.io/cloud-builders/go"
    env: ["GOPATH=/workspace/plugins", "CGO_ENABLED=0"]
    args: ["build", "-tags", "netgo", "-o", "/workspace/googledns", "."]
    dir: 'plugins/src/github.com/kelseyhightower/dns01-exec-plugins/googledns'
    id: "go-build-googledns"

  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=kube-cert-manager", "CGO_ENABLED=0"]
    args: ["build", "-tags", "netgo", "."]
    id: "go-build-kube-cert-manager"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/kube-cert-manager:0.8.0", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/kube-cert-manager:0.8.0"]
